<a href="https://colab.research.google.com/github/ranjithtg-omr/AI_ML_RANJITH/blob/main/Numpy_and_Pandas_(Assignment).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy and Pandas Problems

In [ ]:
import numpy as np



1.Create an array of numbers from 1 to 20 and reshape it into a 4×5 matrix.


In [ ]:
Number1 = np.arange(1,21)
Number1
print("The array of number is ", Number1)

The array of number is  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
Number1=np.reshape(Number1,(4,5))
Number1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

2. Create an array of 10 zeros and replace the 5th element with 100.

In [ ]:
Number1= np.zeros(10)
Number1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
Number1[4]=100
Number1

array([  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.])

3.Create a NumPy array of even numbers between 2 and 40."

In [ ]:
Number1 = np.arange(2,41,2)
Number1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])



4. Generate a 1D array of 15 random integers between 1 and 100 and find its min, max, mean, and standard deviation.


In [ ]:
np.random.seed(42)

In [ ]:
random_integers = np.random.randint(1,101,15)
random_integers

array([ 52,  93,  15,  72,  61,  21,  83,  87,  75,  75,  88, 100,  24,
         3,  22])

In [ ]:
random_integers.min()

np.int64(3)

In [ ]:
random_integers.max()

np.int64(100)

In [ ]:
random_integers.mean()

np.float64(58.06666666666667)

In [ ]:
random_integers.std()

np.float64(31.4843170836247)

5.Given two arrays of sales and costs, calculate profit and profit percentage arrays.

In [ ]:
sales = np.array([1000, 2000, 3000, 4000, 5000])
costs = np.array([500, 1000, 1500, 2000, 2500])

profit = sales - costs
profit
print("The Profit is ", profit)

The Profit is  [ 500 1000 1500 2000 2500]


In [ ]:
profit_per = (profit / sales) * 100
profit_per.round(2)

array([50., 50., 50., 50., 50.])

6. Create a 6×6 random matrix and compute row sums, column sums, and total sum.

In [ ]:
np.random.seed(10)

In [ ]:
Matrix = np.random.randint(1,100, size=(6,6))
Matrix


array([[10, 16, 65, 29, 90, 94],
       [30,  9, 74,  1, 41, 37],
       [17, 12, 55, 89, 63, 34],
       [73, 79, 50, 52, 55, 78],
       [70, 14, 26, 14, 93, 87],
       [31, 31, 90, 13, 66, 32]])

In [ ]:
print("Row sum :" ,Matrix.sum(axis=1))

Row sum : [304 192 270 387 304 263]


In [ ]:
print("Column sums: ", Matrix.sum(axis=0))

Column sums:  [231 161 360 198 408 362]


In [ ]:
print(" total sum:" ,Matrix.sum())

 total sum: 1720


7.Given stock prices, compute daily returns using vectorized NumPy operations.

In [ ]:
prices = np.array([100, 102, 98, 105, 107, 103, 110])
daily_returns = (prices[1:] - prices[:-1]) / prices[:-1]
print("Stock Prices:", prices)
print("Daily Returns:", daily_returns.round(4))

Stock Prices: [100 102  98 105 107 103 110]
Daily Returns: [ 0.02   -0.0392  0.0714  0.019  -0.0374  0.068 ]


8.Convert an array of annual interest rates into monthly rates using vectorization.

In [ ]:
annual_rates = np.array([0.06, 0.08, 0.12, 0.05])
monthly_rates = annual_rates / 12
print("Annual Interest Rates:", annual_rates)
print("Monthly Interest Rates:", monthly_rates.round(4))

Annual Interest Rates: [0.06 0.08 0.12 0.05]
Monthly Interest Rates: [0.005  0.0067 0.01   0.0042]


9.Normalize a given array of portfolio weights so that the sum becomes 1.

In [ ]:
weights = np.array([30, 25, 20, 15, 10])
normalized_weights = weights / weights.sum()
print("Original weights:", weights)
print("Normalized (sum=1):", normalized_weights.round(4))

Original weights: [30 25 20 15 10]
Normalized (sum=1): [0.3  0.25 0.2  0.15 0.1 ]


10.  Create a Pandas Series from the following list: [1200, 1500, 1800, 2000, 2200]

In [ ]:
import pandas as pd

In [ ]:
data = [1200, 1500, 1800, 2000, 2200]
s = pd.Series(data, index=['Monday', 'Tuesday', 'wednsday', 'Thursday', 'Friday'])
print("Series:\n", s)
print("Mean:", s.mean())
print("Max:", s.max())
print("Index of max:", s.idxmax())  # or s.index[s.argmax()]

Series:
 Monday      1200
Tuesday     1500
wednsday    1800
Thursday    2000
Friday      2200
dtype: int64
Mean: 1740.0
Max: 2200
Index of max: Friday


11. Student Marks DataFrame

In [ ]:
df_stud = pd.DataFrame({
    'Name': ['Ranjith', 'Rahul', 'Nithin', 'Navin','Nikhil'],
    'HINDI': [77, 55, 56, 90,77],
    'MALAYALAM': [98, 99, 71, 39,67],
    'ENGLISH': [99, 66, 75, 50,68]
})

print("Full DataFrame:\n", df_stud)
print("ENGLISH column:\n", df_stud['ENGLISH'])
print("First 2 rows:\n", df_stud.head(2))
print("Shape:", df_stud.shape)

Full DataFrame:
       Name  HINDI  MALAYALAM  ENGLISH
0  Ranjith     77         98       99
1    Rahul     55         99       66
2   Nithin     56         71       75
3    Navin     90         39       50
4   Nikhil     77         67       68
ENGLISH column:
 0    99
1    66
2    75
3    50
4    68
Name: ENGLISH, dtype: int64
First 2 rows:
       Name  HINDI  MALAYALAM  ENGLISH
0  Ranjith     77         98       99
1    Rahul     55         99       66
Shape: (5, 4)


12. Account Balance Filtering

In [ ]:
df = pd.DataFrame({
    "Account Number": [2000091, 2000092,2000093, 2000094,2000095],
    "Bank Balance": [500000, 150000, 170000, 120000,340000]
})
print("Original DF:\n", df)
print("Bank Balance > 250000:\n", df[df['Bank Balance'] > 250000])
print("Bank Balance between 100000 and 300000:\n",
      df[df['Bank Balance'].between(100000, 300000)])


Original DF:
    Account Number  Bank Balance
0         2000091        500000
1         2000092        150000
2         2000093        170000
3         2000094        120000
4         2000095        340000
Bank Balance > 250000:
    Account Number  Bank Balance
0         2000091        500000
4         2000095        340000
Bank Balance between 100000 and 300000:
    Account Number  Bank Balance
1         2000092        150000
2         2000093        170000
3         2000094        120000
